require.config({
	baseUrl:"/",
	paths:{
		"jquery":"lib/jquery/jquery-1.12.4",
		"cookie":"lib/jquery_plugins/jquery.cookie",
		"template":"lib/arttemplate/template-native",
		"load":"js/loadheader"
	}
})